application: cocokalamap
version: 1-1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(css|js|images|fonts|tmpl)/(.*)
  static_files: static/\1/\2
  upload: static/.*
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /admin(/.*)?
  script: admin.url.app
  login: admin
- url: /.*
  script: app.url.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:
- datastore.db
- datastore.db-journal
- ^(.*/)?app\.ya?ml
- ^(.*/)?index\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.scss
- ^(.*/)?.*\.less
- ^/docs*
