application: cocokalamap
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(css|js|images|fonts|tmpl)/(.*)
  static_files: static/\1/\2
  upload: static/.*
  expiration: '1d'
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /admin(/.*)?
  script: admin.url.app
  login: admin
- url: /.*
  script: app.url.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
